//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDFilmsAvisContext : DbContext
    {
        public BDFilmsAvisContext()
            : base("name=BDFilmsAvisContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_E_AVIS_AVI> T_E_AVIS_AVI { get; set; }
        public virtual DbSet<T_E_COMPTE_CPT> T_E_COMPTE_CPT { get; set; }
        public virtual DbSet<T_E_FILM_FLM> T_E_FILM_FLM { get; set; }
    }
}
